---
title: "Coding Style"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Coding Style}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Founding principles of good analysis
 

 *   `Reproducibility` -  guarantees that we have done what we are claiming to have done, and that others can easily replicate our work.

 *   `Auditability` -  means that we know why we chose our analysis, and who is responsible for each part of it - including assurance.

 *   `Assurance` -  improves the average quality and includes the communication of that quality to users.


## Coding style

Unlike some other languages R is very flexible in how your code can be formatted. Whatever coding style you prefer it is important to be consistent. This makes your code easier to read and makes it easier for other people to contribute to it. It is useful to document what coding style you are using. 

Options are: 
 *   `Tidyverse` -  https://style.tidyverse.org/
 *   `Google` -  https://google.github.io/styleguide/Rguide.html
 *   `Jean Fan` -  https://jef.works/R-style-guide/

## Version package

This version number follows the format major.minor.patch.dev. The different parts of the version represent different things:

 *   `major` - A significant change to the package that would be expected to break users code. This is updated very rarely when the package has been redesigned in some way.
 
 *   `minor` - A minor version update means that new functionality has been added to the package. It might be new functions to improvements to existing functions that are compatible with most existing code.
 
 *    `patch` - Patch updates are bug fixes. They solve existing issues but don’t do anything new.