---
title: "Showcase"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Showcase}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

 

Any project, i.e. Training material, presentation or highlighted analysis, can be included in the `{unhcRverse}` Showcase vignette though a [issue posted in this current repository](https://github.com/unhcRverse/unhcRverse/issues).  Community members will provide feedback through discussion in the issue system and unless some strong reservation are raised, the project will referenced in the vignette within one month.

Having a project referenced here is for authors:

 * A recognition of the project and an way to showcase the work done in order to inspire colleagues.

 * An opportunity to request and benefit from peer review from all R-users within UNHCR and potentially third-party support.

 * An opportunity to be identified as an R-champions and of having a "word to say" in the governance of the `unhcRverse`


Note that you can also find good references in the inter-agency [humanitarian-user-group](https://humanitarian-user-group.github.io/) and join the [linked interagency skype group](https://join.skype.com/qYBKC5q3wKp4). Last as UNHCR staff, you can also join the [internal UNHCR R discussion on Microsoft Team](https://teams.microsoft.com/l/team/19%3abJPOOPqjzEEM31OYga5Jzw8mqGxDb_V2EKJedvKIims1%40thread.tacv2/conversations?groupId=68d8e31a-a244-479b-8467-4dc6bf9b7fdd&tenantId=e5c37981-6664-4134-8a0c-6543d2af80be)

 
Below is an initial listing of showcased repositories:


## R Training

 * https://github.com/unhcr-americas/reproducibility
 * https://github.com/vidonne/unhcRstyle_workshop
 * https://github.com/dickoa/panafrican-dima-r-training 
 * https://github.com/unhcr-americas/SurveyAnalysisTutorial
 * https://edouard-legoupil.github.io/kobocruncher/#tutorial
 

## Data Scrapping

 * https://github.com/unhcr-americas/usastats
 * https://github.com/PopulationStatistics/Eurostats
 * https://github.com/unhcr-americas/darien_gap_human_mobility
 * https://github.com/unhcr-americas/iati
 * https://github.com/unhcr-americas/IatiTidy
 
## Activities Tracking

 * https://github.com/MatayoBweta/three_rp_planning
 * https://github.com/response4venezuelans/R4RMRP2022
 * https://github.com/response4venezuelans/Submission2324QualityApp
 * https://github.com/unhcr-americas/weekly-report

## Statistical Quality Control

 * https://github.com/PopulationStatistics/StatisticalQualityAssurance
 * https://github.com/PopulationStatistics/StatisticsCore

## Survey Management

 * https://github.com/MatayoBweta/shiny_question_scoring_system
 * https://github.com/unhcr-americas/surveyDesigner
 * https://github.com/unhcr-americas/DataCollectionMonitoring

## UNHCR RBM (Result Based Management) "survey indicator" calculation

 * https://github.com/bozdagilgi/UNHCR-RMS-Indicators
 * https://github.com/bozdagilgi/UNHCR-BFA-RMS-2022
 * https://github.com/bozdagilgi/UNHCR-ETH-RMS-IDP-2022
 * https://github.com/bozdagilgi/UNHCR-RMS-ETH-RAS-2022
 * https://github.com/UNHCR-CostaRica/ENAHOrbm

## Datavisualisation

 * https://github.com/TadeHabte/shiny-with-flexdashboard
 * https://github.com/TadeHabte/Animation-in-R
 * https://github.com/TadeHabte/Drill_down

## Registration Data Analysis 

 * https://github.com/unhcr-americas/proGres-analysis

## Composite indicators 

 * https://github.com/unhcr-mena/analytic-hierarchy-process
 * https://github.com/unhcr-americas/vulnerability-scoring
 * https://github.com/unhcr-americas/Area_Based_Approach
 * https://github.com/unhcr-mauritania/model

## Reproducible data analysis & data story telling examples

 * https://github.com/unhcr-americas/ageingonthemove
 * https://github.com/unhcr-americas/riadis
 * https://github.com/UNHCR-WEB/R-usergroup
 * https://github.com/unhcr-americas/Americas-Protection-Monitoring_2020
 * https://github.com/unhcr-americas/VenSit_PM_2020
 * https://github.com/unhcr-americas/RegionalTrends
 * https://github.com/unhcr-americas/LAPOP-SMA
 * https://github.com/unhcr-mena/focus-analysis