# WARNING - Generated by {fusen} from dev/dev_fusen.Rmd: do not edit by hand

test_that("update_github works", {
  expect_true(inherits(update_github, "function"))
  expect_equal(update_github("testthat"), "Done!")
})
