# WARNING - Generated by {fusen} from dev/dev_fusen.Rmd: do not edit by hand


test_that("check_github works", {
  expect_true(inherits(check_github, "function")) 
  
  pkg <- "r-lib/pkgdown"
  result <- check_github(pkg)
  
  url <- paste0("https://raw.githubusercontent.com/", pkg, "/master/DESCRIPTION")
  x <- readLines(url)
  remote_version <- gsub("Version:\\s*", "", x[grep('Version:', x)])
  
  installed_version <- tryCatch(packageVersion(gsub(".*/", "", pkg)), error=function(e) NA)
  
  
  expect_is(result, "list")
  expect_equal(result$latest_version, remote_version)
 
  # if (remote_version > installed_version) {
  #   expect_equal(result$up_to_date, FALSE)
  # } else if (remote_version == installed_version) {
  #   expect_equal(result$up_to_date, TRUE) }
  
})
