# WARNING - Generated by {fusen} from dev/dev_fusen.Rmd: do not edit by hand

test_that("unhcrverse works", {
  expect_true(inherits(unhcrverse, "function"))   
 # expect_equal(unhcrverse(), NULL)
 #  expect_equal(unhcrverse(dev = TRUE), NULL)
})
