---
title:  Survey Companion App Toolbox
subtitle: "Improving the quality of survey data on forcibly displaced populations"
format: unhcr-revealjs
embed-resources: true
---
 
## Let's talk Quality!
 
 * Microdata quality in surveys on Forcibly Displaced Populations not only determines the reliability of currently collected information, but also the __quality of any future information__, such as remote sensing data, which requires validation through primary data.
 
 * Any errors introduced during the data collection process of the primary data, will most likely also create further issues with the information __reliability__ in the future. 
 
 * This can __negatively__ influence program design, protection advocacy and policy making
  

## The Companion App Survey Toolkit 

Need to get tools for field staff with minimal programming skills, that can enhance the overall quality of survey data and support: 

 * Sampling design 
 * Questionnaire design 
 * Data Collection Monitoring
 * Data Analysis 

Mirroring [WB "Survey Solution" project (JDC)](https://www.jointdatacenter.org/improving-the-quality-of-survey-data-on-forcibly-displaced-populations/)...

::: {.notes}
all of which are critical in improving the quality of the data collected and managed on populations affected by forced displacement. With the scope of guaranteeing quality in the different stages of survey design and implementation, this project proposes different tools and methods for:

To cover the target populations in different population settings (i.e. returnee vs. IDPs, host- vs. camp-population) with the most effective sample design, the tool will allow implementation not only of standard sampling approaches (i.e. two stage stratified area sample), which can be used to sample households in host communities, as well as: Sampling from a spatial grid in the absence of any existing area- or list-frame;  Use of gridded population data like WorldPop (https://www.worldpop.org/ );Sampling based on other satellite-based data.
  
:::      


## Companion App design

 * Minimal scope - rather multiple simple __companion apps__ to be used at different stages of the whole process than a single complex _do-it-all_ one
 
 * Interface developed to help the diffusion of guidance: __learning by doing__ to be paired with __micro-learning__ for field staff in charge of the implementation on the ground
 
 * Tools built around free or open source solutions and designed to operate in __capacity-constrained environments__ and to enable collaborative development.

## Starting wih sampling frame

The construction of the sampling frame & the selection of the appropriate sampling design is crucial to produce statistically valid estimates that ensure results representativeness

 - Sampling frames are the backbones of __probability-based__ sampling design. They plays one of the main roles in determining quality and reliability for the survey  

 - Available frames often __do not meet basic criteria__: being current, comprehensive and sufficiently informative on the variable(s) of interest in the target population. In addition, target population size can be small and/or the population is hard to reach 



## Companion App {rmsSampling}

:::: {.columns}

::: {.column width="50%"}

Scope: 

 - Start from the country data as from ASR

 - Select the methodology based on a decision tree for each group

 - Define sample size based on expected accuracy

:::

::: {.column width="50%"}

App Maturity: __Alpha-version__ 

 - [Initial Wireframe created](https://rstudio.unhcr.org/rmsSampling/)

 - [ISSUE -- Pending discussion on decision tree](https://github.com/unhcr-americas/rmsSampling/issues/1)

 - [ISSUE -- Adjust sample size calculation based on method](https://github.com/unhcr-americas/rmsSampling/issues/2)

:::

::::
        
## Questionnaire design 

Enabling users planning to collect data, with basic to minimal programming knowledge,  to easily create questionnaires tailored for populations affected by forced displacement. 
 
Questionnaire templates designed to incorporate recommended checks and verifications of question and response options. 

How to implementing multiple interviewing modes during the survey as welll as multiple data collection waves.

## Companion App  {xlsFormUtil}

:::: {.columns}

::: {.column width="50%"}

Scope: 

 - Compare contextualized version with baseline global template

 - Select the methodology based on a decision tree for each group

 - Define sample size based on expected accuracy

:::

::: {.column width="50%"}

App Maturity: __Release-Candidate__ 

 - [Link to app](https://rstudio.unhcr.org/XlsFormUtil/)

:::

::::



## Companion App {surveyDesigner} 

:::: {.columns}

::: {.column width="50%"}

Scope: 

 - Start questionnaire design from indicators selections
 
 - Provide scenarios over multiple data collection an waves and mode to optiomise the cost/quality threshold
  
 
:::

::: {.column width="50%"}

App Maturity: __alpha-version__

 - [Initial Wireframe created](https://rstudio.unhcr.org/Survey_Designer/)
 
 - [ISSUE -- Build cost/quality threshold simulation](https://github.com/unhcr-americas/surveyDesigner/issues/27)
 
 - [ISSUE -- Create a directory of indicators to questions](https://github.com/unhcr-americas/surveyDesigner/issues/22)

:::

::::

##  Fieldwork and data quality assurance


Real time quality monitoring and the use of metadata and paradata facilitate quality control, but often presents challenges for the survey practitioners  

Processing metadata and paradata opens avenues for understanding the behavior of the survey respondents, interviewers and improvement of the questionnaire. 
 


## Companion App {HighFrequencyChecks}


:::: {.columns}

::: {.column width="50%"}

Scope: 

 - Compare contextualized version with baseline global template

 - Select the methodology based on a decision tree for each group

 - Define sample size based on expected accuracy

:::

::: {.column width="50%"}

App Maturity: __beta-version__


 - [Link to app](https://rstudio.unhcr.org/HighFrequencyChecks/) 

:::

::::


##  Data Exploration and Indicator Calculation

Working in Excel for large complex survey dataset is not a sustainable option

Reproducibility is a key element to enforce

## Companion App {koboCruncher} 

:::: {.columns}

::: {.column width="50%"}

Scope: 

 - Ease relabeling, grouping , cross-tabulation
 
 - Direct connection to RIDL to enable data audit

:::

::: {.column width="50%"}

App Maturity: __beta-version__
 

 - [Link to app](https://rstudio.unhcr.org/kobocruncher/) 

:::

::::


## Companion App   {IndicatorCalc}


:::: {.columns}

::: {.column width="50%"}

Scope: 

 - Perform a mapping between a specific suvey and expected variables/modality for on survey
 
 - Ease variable recoding
 
 - Output standard report and dataset for indicators - included directly in RIDL

:::

::: {.column width="50%"}

App Maturity: __beta-version__
 

 - [Link to app](https://rstudio.unhcr.org/IndicatorCalc/) 

:::

::::



## In-details Presentation of the 3 __beta-version__

 - Kobo [Data Collection Management](https://edouard-legoupil.github.io/HighFrequencyChecks/tutorial/index.html) with [`{HighFrequencyChecks}`](https://edouard-legoupil.github.io/HighFrequencyChecks) 
 
 - Kobo [Survey Data Exploration](https://edouard-legoupil.github.io/kobocruncher/tutorial/00-Intro.html#1) with [`{KoboCruncher}`](https://edouard-legoupil.github.io/kobocruncher)
 
 - Apply [Indicator calculations for RMS](https://edouard-legoupil.github.io/IndicatorCalc/tutorial/index.html)