---
title: UnhcrRverse
subtitle: Workshop on UNHCR R Packages
format: unhcr-revealjs
embed-resources: true
---

## Intro

This workshop can not replace __fact-sheet-able certifications__ like the self-paced R training offered through [UNHCR Learn & Connect](https://unhcr.csod.com/ui/lms-learner-playlist/PlaylistDetails?playlistId=e90e2279-e3a4-4ef2-8b74-757f91d224b2). Rather than learning R _in general terms_, the sessions will provide an overview of how R is being used and customized within UNHCR context. 

Each of the 12 sessions (_presentations & exercise_) is organised to last one hour around a __specific learning objective__.

Hands-on Co-Dev sessions between the training facilitator and the operation country team on __practical challenges__ will take place in the afternoon


::: {.notes}
The session will focus on presenting dedicated packages created by UNHCR staff in HQ and in the field.
:::


## Workshop Plan


- Day 1 - Basics of R

- Day 2 - R for Surveys

- Day 3 - R for Reporting

- Day 4 - R for Processes


## Day 1 Morning - Basics of R

 - An introduction to [Analysis Reproducibility](01.Reproducibility)

 - Data [Manipulation and Visualization](02.Tidyverse.html) using [{refugees}](https://populationstatistics.github.io/refugees/) & [{unchrthemes}](https://unhcr-dataviz.github.io/unhcrthemes/), access data through API with [{robotoolbox}](https://dickoa.gitlab.io/robotoolbox/), [{rhdx}](http://dickoa.gitlab.io/rhdx/), [{riddle}](https://edouard-legoupil.github.io/riddle/), [{popdata}](https://edouard-legoupil.github.io/popdata/), [{activityinfo-R}](https://www.activityinfo.org/support/docs/R/)
 
 - From [Scripts to Functions](03.Functions.html): An illustration with [{unhcrplot}](https://edouard-legoupil.github.io/unhcrdatapackage/)
 

# Afternoon 1 - Hands-on {.slide-blue}

Using official Statistics to calculate indicators and build charts
 

## Day 2  Morning - R for Surveys

[The Survey Toolbox](04.SurveyToolbox.html)

 - Kobo [Data Collection Management](https://edouard-legoupil.github.io/HighFrequencyChecks/tutorial/index.html) with [{HighFrequencyChecks}](https://edouard-legoupil.github.io/HighFrequencyChecks/) 
 
 - Kobo [Survey Data Exploration](file:///home/edouard/R-projects/UNHCR_package/kobocruncher/docs/tutorial/00-Intro.html#1) with [{KoboCruncher}](05.KoboCruncher.html)
 
 - Apply [Indicator calculations for RMS](https://edouard-legoupil.github.io/IndicatorCalc/tutorial/index.html) with [{IndicatorCalc}](https://unhcr-americas.github.io/IndicatorCalc/)
 

# Afternoon 2 - Hands-on {.slide-blue}

Working on UNHCR recent household survey dataset 
 
 
## Day 3 Morning -  R for Reporting
 
 - "Work as a Team": Collaboration through [Version Control](07.VersionControl.html) on Github. 
 
 - Build wth [Report Template](08.Template_Report.html) with [{unhcrdown}](https://unhcr-dataviz.github.io/unhcrdown/) and [Posit Connect](http://rstudio.unhcr.org): An example with [weekly report](https://github.com/unhcr-americas/weekly-report) 
 
 - [Automating Tips](09.Automate_generation.html) https://github.com/vidonne/r-tips#tips to set up reproducible analysis pipeline
 
 

# Afternoon 3 - Hands-on {.slide-blue}

Developing a presentation from a survey

Facilitating Data Interpretation


## Day 4 Morning -  R for Processes 
 
 - [Package knowledege](10.Package_Knowledge.html): Development, Documentation & Testing with [{fusen}](https://thinkr-open.github.io/fusen), illustrated with [{unhcrdataportal/}](https://edouard-legoupil.github.io/unhcrdataportal/)
 
 - Create [Shiny Companion App](11.Simplify_with_companionApp.html) with [{Graveler}](https://edouard-legoupil.github.io/graveler/) 
 
 - Building [Severity index](https://rstudio.unhcr.org/SeverityIndex/): an overview of [{A2SIT}](https://rstudio.unhcr.org/SeverityIndex/)
 
  

# Afternoon 4 - Hands-on {.slide-blue}

Quick Dashboard creation with Shiny

Organizing data for severity index



# Webinar rules

<i class="fa fa-spinner fa-spin fa-fw fa-2x"></i> Leverage this opportunity and make this session __lively__ - there's no stupid questions!

 

<i class="fa fa-pencil  fa-fw fa-2x"></i> No need to take notes, all the session __content__ will be shared 

<i class="fa fa-cog fa-fw fa-2x"></i> All practical exercises are designed to get you __testing the commands__:

::: {.notes}
> Login on a dedicated cloud-based version of RStudio with base packages pre-installed for this session @ 
    
> Paste the command from the chat to your online Rstudio session and check what is happening
    
> In case it is not working as expected, share screenshot or error messages from the console in the chat
::: 


