---
title: UNHCRverse
subtitle: Workshop on UNHCR Packages
format: unhcr-revealjs
embed-resources: true
---


## Workshop Plan

Presentation in the morning, hands-on session in the afternoon

- Day 1 - Basics of R

- Day 2 - R for Surveys

- Day  - R for Reporting

- Day 4 - R for Processes


## Day 1 Morning - Basics of R

 - An introduction: Analysis Reproducibility

 - Data Manipulation and Visualization - using {refugees} & {unchrthemes}
 
 - Building functions: An overview of {unhcrplot}
 
 - Accessing data api: {robotoolbox}, {riddle}, {rhdx}
 

## Day 1 Afternoon - Hands-on

Hands on session - using official Statistics to build charts
 

## Day 2  Morning - R for Surveys

 - Kobo Survey Management with {HighFrequencyChecks} 
 
 - Kobosurvey Data Exploration with {KoboCruncher}
 
 - Indicator calculation for RMS with {IndicatorCalc}
 

## Day 2 Afternoon - Hands-on

Working on UNHCR recent household survey dataset 
 
 
## Day 3 Morning -  R for Reporting
 
 - Reporting with {unhcrdown} and Posit Connect: An example with weekly report 
 
 - Collaborative report building under version control with github. 
 

## Day 3 Afternoon - Hands-on

Developing a presentation from a survey

Facilitating Data Interpretation


## Day 4 Morning -  R for Processes 
 
 - Building index: an overview of {A2SIT}
 
 - Package building & ShinyApp creation with {Graveler} 
  

## Day 4 Afternoon - Hands-on

Organizing data for severity index
