# WARNING - Generated by {fusen} from dev/dev_fusen.Rmd: do not edit by hand

#' unhcrverse
#' 
#' check and load latest version of unhcrverse
#' 
#' @return nothing only messages
#' @param dev Boolean TRUE / FALSE to indicate if the dev version should be used
#' @return list
#' @export
#' @examples
#'
#' # install.packages("pak")
#' # pak::pkg_install("unhcRverse/unhcRverse")
#'
#' # unhcrverse::unhcrverse() 
#'
#' ## If you want to contribute to package development, 
#' # which you are probably if you are currently checking this test :)
#' # use the version from the developers
#' # unhcrverse::unhcrverse(dev = TRUE)

unhcrverse <- function( dev = FALSE) {
  message("Welcome to {unhcrverse}! ")
  message("--------------------- ")
  message("There are currently a few packages in {unhcrverse}.")
  message("We will check if you have the required package (or the last version) in your system and install them if necessary! ")
  message("--------------------- ")
  
  if( dev == TRUE ) {
    message( "You decided to install the development versions for each component of unhcRverse. ")
    message(" Current Development version of the packages are within respective maintainer personal account")
  } else {
    message( "You are installing the most stable version from https://github.com/unhcRverse ")
  }
  
  
  ## Core Dev - Cedric Vidonne
  
    if( dev == TRUE ) {
       chck <- check_github('vidonne/unhcrthemes')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {update_github('unhcr-dataviz/unhcrthemes')}
    } else {
       chck <- check_github('unhcrverse/unhcrthemes')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcr-dataviz/unhcrthemes')  }
    }
  
    if( dev == TRUE ) {
       chck <- check_github('vidonne/unhcrdown')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {   update_github('unhcr-dataviz/unhcrdown')}
    } else {
       chck <- check_github('unhcrverse/unhcrdown')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('unhcr-dataviz/unhcrdown')  }
    }
  
 
  
  ## Core Dev - Ahmadou Dicko
  
    if( dev == TRUE ) {
       chck <- check_github('PopulationStatistics/popdata')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('PopulationStatistics/popdata')}
    } else {
       chck <- check_github('PopulationStatistics/popdata')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {   update_github('PopulationStatistics/popdata')  }
    }
    if( dev == TRUE ) {
       chck <- check_github('PopulationStatistics/refugees')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('PopulationStatistics/refugees')}
    } else {
       chck <- check_github('PopulationStatistics/refugees')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {   update_github('PopulationStatistics/refugees')  }
    }
  
 
  
    if( dev == TRUE ) {
       chck <- check_github('dickoa/rhdx')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('dickoa/rhdx')}
    } else {
       chck <- check_github('dickoa/rhdx')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('dickoa/rhdx') }
  }
    if( dev == TRUE ) {
       chck <- check_github('dickoa/robotoolbox')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('dickoa/robotoolbox')}
    } else {
       chck <- check_github('dickoa/robotoolbox')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('dickoa/robotoolbox')  }
  }
  
  
  ## Core Dev - Edouard Legoupil
    if( dev == TRUE ) {
       chck <- check_github('Edouard-Legoupil/graveler')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('Edouard-Legoupil/graveler')}
    } else {
       chck <- check_github('Edouard-Legoupil/graveler')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('Edouard-Legoupil/graveler')}
    }
  
    if( dev == TRUE ) {
       chck <- check_github('Edouard-Legoupil/riddle')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('Edouard-Legoupil/riddle')}
    } else {
       chck <- check_github('Edouard-Legoupil/riddle')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('Edouard-Legoupil/riddle')}
      }
  
    if( dev == TRUE ) {
       chck <- check_github('edouard-legoupil/HighFrequencyChecks')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('edouard-legoupil/HighFrequencyChecks')}
    } else {
       chck <- check_github('edouard-legoupil/HighFrequencyChecks')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('edouard-legoupil/HighFrequencyChecks')}
      }
      
    if( dev == TRUE ) {
       chck <- check_github('edouard-legoupil/kobocruncher')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('edouard-legoupil/kobocruncher')}
    } else {
       chck <- check_github('edouard-legoupil/kobocruncher')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {update_github('edouard-legoupil/kobocruncher')  }
    }
  
    if( dev == TRUE ) {
       chck <- check_github('edouard-legoupil/unhcrdatapackage')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('edouard-legoupil/unhcrdatapackage')}
    } else {
       chck <- check_github('edouard-legoupil/unhcrdatapackage')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('edouard-legoupil/unhcrdatapackage')  }
    }
  
    if( dev == TRUE ) {
       chck <- check_github('unhcr-americas/XlsFormUtil')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcr-americas/XlsFormUtil')}
    } else {
       chck <- check_github('unhcr-americas/XlsFormUtil')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcr-americas/XlsFormUtil')}
    }
  return(NULL)
}


