# WARNING - Generated by {fusen} from /dev/dev_fusen.Rmd: do not edit by hand

#' unhcrverse
#' 
#' check and load latest version of unhcrverse
#' 
#' @return nothing only messages
#' @param dev Boolean TRUE / FALSE to indicate if the dev version should be used
#' @return list
#' @export

#' @examples
#' 
#' # install.packages("pak")
#' # pak::pkg_install("unhcRverse/unhcRverse")
#' 
#' # unhcrverse::unhcrverse() 
#' 
#' ## If you want to contribute to package development, 
#' # which you are probably if you are currently checking this test :)
#' # use the version from the developers
#' # unhcrverse::unhcrverse(dev = TRUE)
unhcrverse <- function( dev = FALSE) {
  message("Welcome to {unhcrverse}! ")
  message("--------------------- ")
  message("There are currently 12 packages in {unhcrverse}.")
  message("We will check if you have the required package (or the last version) in your system and install them if necessary! ")
  message("--------------------- ")
  
  if( dev == TRUE ) {
    message( "You decided to install the development versions for each component of unhcRverse. ")
    message(" Current Development version of the packages are within respective maintainer personal account")
  } else {
    message( "You are installing the most stable version from https://github.com/unhcRverse ")
  }
  
  
  ## Core Dev - Cedric Vidonne
  
    if( dev == TRUE ) {
       chck <- check_github('vidonne/unhcrthemes')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {update_github('vidonne/unhcrthemes')}
    } else {
       chck <- check_github('unhcrverse/unhcrthemes')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcrverse/unhcrthemes')  }
    }
    if( dev == TRUE ) {
       chck <- check_github('vidonne/unhcrdown')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {   update_github('vidonne/unhcrdown')}
    } else {
       chck <- check_github('unhcrverse/unhcrdown')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('unhcrverse/unhcrdown')  }
    }
  
  
    if( dev == TRUE ) {
       chck <- check_github('vidonne/unhcrdesign')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('vidonne/unhcrdesign')}
    } else {
       chck <- check_github('unhcrverse/unhcrdesign')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcrverse/unhcrdesign')    }
    }
  
    if( dev == TRUE ) {
       chck <- check_github('vidonne/unhcrtemplate')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('vidonne/unhcrtemplate')}
    } else {
       chck <- check_github('unhcrverse/unhcrtemplate')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('unhcrverse/unhcrtemplate') }
  }
  
  ## Core Dev - Ahmadou Dicko
  
    if( dev == TRUE ) {
       chck <- check_github('PopulationStatistics/popdata')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('PopulationStatistics/popdata')}
    } else {
       chck <- check_github('unhcrverse/popdata')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {   update_github('unhcrverse/popdata')  }
    }
  
    if( dev == TRUE ) {
       chck <- check_github('dickoa/ridl')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('dickoa/ridl')}
    } else {
       chck <- check_github('unhcrverse/ridl')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcrverse/ridl')}
    }
  
    if( dev == TRUE ) {
       chck <- check_github('dickoa/rhdx')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('dickoa/rhdx')}
    } else {
       chck <- check_github('unhcrverse/rhdx')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('unhcrverse/rhdx') }
  }
    if( dev == TRUE ) {
       chck <- check_github('dickoa/robotoolbox')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('dickoa/robotoolbox')}
    } else {
       chck <- check_github('unhcrverse/robotoolbox')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcrverse/robotoolbox')  }
  }
  
  
  ## Core Dev - Edouard Legoupil
  
    if( dev == TRUE ) {
       chck <- check_github('edouard-legoupil/HighFrequencyChecks')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {  update_github('edouard-legoupil/HighFrequencyChecks')}
    } else {
       chck <- check_github('unhcrverse/HighFrequencyChecks')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcrverse/HighFrequencyChecks')}
      }
      
    if( dev == TRUE ) {
       chck <- check_github('edouard-legoupil/kobocruncher')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('edouard-legoupil/kobocruncher')}
    } else {
       chck <- check_github('unhcrverse/kobocruncher')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) {update_github('unhcrverse/kobocruncher')  }
    }
  
    if( dev == TRUE ) {
       chck <- check_github('edouard-legoupil/unhcrdatapackage')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('edouard-legoupil/unhcrdatapackage')}
    } else {
       chck <- check_github('unhcrverse/unhcrdatapackage')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcrverse/unhcrdatapackage')  }
    }
  
    if( dev == TRUE ) {
       chck <- check_github('edouard-legoupil/XlsFormPrettyPrint')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('edouard-legoupil/XlsFormPrettyPrint')}
    } else {
       chck <- check_github('unhcrverse/XlsFormPrettyPrint')
       if( chck$up_to_date == FALSE | is.na( chck$up_to_date) ) { update_github('unhcrverse/XlsFormPrettyPrint')}
    }
  return(NULL)
}


