# WARNING - Generated by {fusen} from /dev/dev_fusen.Rmd: do not edit by hand

#' update_github
#' 
#' Update package from github
#' 
#' @param pkg
#' 
#' @importFrom utils installed.packages packageDescription
#' @importFrom pak pkg_install
#' 
#' @return nothing just messaging what is happening
#' 
#' @export
#' 

#' @examples
#' # No example - cf - 
#' ## https://github.com/r-lib/pkgcache#using-pkgcache-in-cran-packages
#' 
#' # update_github(pkg = 'vidonne/unhcrthemes')
#' 
#' 
#'      
update_github <- function( pkg) {
  message(paste("## Upgrading or installing packages: ", pkg, " now..."))
  pak::pkg_install(pkg = pkg)
  return(paste0("Done!"))
}

